name: Build Serotonin

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Build Serotonin
    runs-on: macos-latest
    env:
      THEOS: ${{ github.workspace }}/theos

    steps:
      - name: 🚚 Check out the Repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          submodules: true

      - name: 💾 Install System Dependencies
        run: brew install ldid-procursus make

      - name: 🔍 Check cache
        run: echo upstream_heads=`git ls-remote https://github.com/theos/theos | head -n 1 | cut -f 1`-`git ls-remote https://github.com/theos/sdks | head -n 1 | cut -f 1` >> $GITHUB_ENV

      - name: ♻️ Restore cache if available
        id: cache
        uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ env.upstream_heads }}

      - name: ⚙️ Setup Theos
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: theos/theos
          path: theos
          submodules: recursive

      - name: ⚙️ Setup iOS SDK
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: theos/sdks
          path: theos/sdks
          sparse-checkout: "iPhoneOS16.5.sdk"
          sparse-checkout-cone-mode: false

      - name: ♻️ Save cache if needed
        if: steps.cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9 # v4.0.2
        with:
          path: ${{ github.workspace }}/theos
          key: ${{ env.upstream_heads }}

      - name: 💾 Download ct_bypass to /usr/local/bin
        run: |
          curl -L -o /usr/local/bin/ct_bypass https://cdn.mineek.dev/serotonin/action_deps/ct_bypass
          chmod +x /usr/local/bin/ct_bypass

      - name: 📦 Compile IPA
        run: gmake FINALPACKAGE=1

      - name: 🚀 Upload IPA
        uses: actions/upload-artifact@0b2256b8c012f0828dc542b3febcab082c67f72b # v4.3.4
        with:
          name: Serotonin CI Build
          path: Serotonin.tipa
